{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-16228", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:21 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-09-11", "cve_detail": "", "references": [{"URL": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE", "Description": "MISC:https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-09-11"}