{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-15486", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:19 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-08-23", "cve_detail": "", "references": [{"URL": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1", "Description": "MISC:https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1"}, {"URL": "https://github.com/ierror/django-js-reverse/pull/81", "Description": "MISC:https://github.com/ierror/django-js-reverse/pull/81"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-08-23"}