{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-16226", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:21 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-09-11", "cve_detail": "", "references": [{"URL": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln", "Description": "MISC:https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-09-11"}