{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-16729", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:23 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-09-24", "cve_detail": "", "references": [{"URL": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1", "Description": "MISC:https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1"}, {"URL": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/", "Description": "MISC:https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/"}, {"URL": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/", "Description": "MISC:https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-09-24"}