{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-12565", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in Linaro LAVA before 2018.5.post1. Because of use of yaml.load() instead of yaml.safe_load() when parsing user data, remote code execution can occur.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:20 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-06-25", "cve_detail": "", "references": [{"URL": "https://git.linaro.org/lava/lava.git/commit/?id=583666c84ea2f12797a3eb71392bcb05782f5b14", "Description": "CONFIRM:https://git.linaro.org/lava/lava.git/commit/?id=583666c84ea2f12797a3eb71392bcb05782f5b14"}, {"URL": "https://www.debian.org/security/2018/dsa-4234", "Description": "DEBIAN:DSA-4234"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-06-19"}