{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2015-5145", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:02:50 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2017-09-21", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/75691", "Description": "BID:75691"}, {"URL": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/", "Description": "CONFIRM:https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"}, {"URL": "https://security.gentoo.org/glsa/201510-06", "Description": "GENTOO:GLSA-201510-06"}, {"URL": "http://www.securitytracker.com/id/1032820", "Description": "SECTRACK:1032820"}], "cve_repaire": "", "editor": "warcup", "add_time": "2015-07-14"}