{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2016-10127", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:01:30 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2017-03-06", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/95376", "Description": "BID:95376"}, {"URL": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716", "Description": "MISC:https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"}, {"URL": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b", "Description": "MISC:https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"}, {"URL": "https://github.com/rohe/pysaml2/issues/366", "Description": "MISC:https://github.com/rohe/pysaml2/issues/366"}, {"URL": "https://github.com/rohe/pysaml2/pull/379", "Description": "MISC:https://github.com/rohe/pysaml2/pull/379"}, {"URL": "http://www.openwall.com/lists/oss-security/2017/01/19/5", "Description": "MLIST:[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-03-03"}